# Ensure that the plugin meets the required style guidelines
# Ensure that the plugin builds correctly

name: CI Checks

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Deps
        run: |
          pip install -U flake8 pep8-naming
          pip install -U wheel setuptools twine build
      - name: Style Checks
        run: |
          flake8 .
      - name: Build Plugin
        run: |
          python -m build
  
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build --emptyOutDir